// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRxVjJ_Kgx9hj5XVZiA58zL3eG0BdmSs',
    appId: '1:457275280899:web:bb72178cd70c3ea115c836',
    messagingSenderId: '457275280899',
    projectId: 'faster-5d279',
    authDomain: 'faster-5d279.firebaseapp.com',
    databaseURL: 'https://faster-5d279-default-rtdb.firebaseio.com',
    storageBucket: 'faster-5d279.firebasestorage.app',
    measurementId: 'G-DDP3F306JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADAMw_7i70ShVb2DW-yImOAvoTlV74U74',
    appId: '1:457275280899:android:ee4b2dabdb5d5a0115c836',
    messagingSenderId: '457275280899',
    projectId: 'faster-5d279',
    databaseURL: 'https://faster-5d279-default-rtdb.firebaseio.com',
    storageBucket: 'faster-5d279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQSHJVRWHOgw2M7If4sZ03EkkA6JAJ2no',
    appId: '1:457275280899:ios:94e45fd92bab5ce815c836',
    messagingSenderId: '457275280899',
    projectId: 'faster-5d279',
    databaseURL: 'https://faster-5d279-default-rtdb.firebaseio.com',
    storageBucket: 'faster-5d279.firebasestorage.app',
    iosBundleId: 'com.faster.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQSHJVRWHOgw2M7If4sZ03EkkA6JAJ2no',
    appId: '1:457275280899:ios:94e45fd92bab5ce815c836',
    messagingSenderId: '457275280899',
    projectId: 'faster-5d279',
    databaseURL: 'https://faster-5d279-default-rtdb.firebaseio.com',
    storageBucket: 'faster-5d279.firebasestorage.app',
    iosBundleId: 'com.faster.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzRxVjJ_Kgx9hj5XVZiA58zL3eG0BdmSs',
    appId: '1:457275280899:web:9f51ec8924ab1c6815c836',
    messagingSenderId: '457275280899',
    projectId: 'faster-5d279',
    authDomain: 'faster-5d279.firebaseapp.com',
    databaseURL: 'https://faster-5d279-default-rtdb.firebaseio.com',
    storageBucket: 'faster-5d279.firebasestorage.app',
    measurementId: 'G-QJL0BKGZC8',
  );
}
