platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  # Paymob iOS SDK for payment processing
  pod 'PaymobSDK', '~> 1.0.20'

  target 'RunnerTests' do
    inherit! :complete
  end

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end