/*
  Migration: Provider schedule table and upsert RPC
*/

-- Table to store provider availability slots
CREATE TABLE IF NOT EXISTS provider_schedules (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  provider_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  day_of_week SMALLINT NOT NULL,  -- 1 = Monday, ..., 7 = Sunday
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Indexes for efficient lookups
CREATE INDEX IF NOT EXISTS idx_provider_schedules_provider ON provider_schedules(provider_id);
CREATE INDEX IF NOT EXISTS idx_provider_schedules_day ON provider_schedules(day_of_week);

-- Row level security: providers can only manage their own schedules
ALTER TABLE provider_schedules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Providers can insert own schedule" ON provider_schedules
  FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = provider_id);
CREATE POLICY "Providers can update own schedule" ON provider_schedules
  FOR UPDATE TO authenticated
  USING (auth.uid() = provider_id);
CREATE POLICY "Providers can delete own schedule" ON provider_schedules
  FOR DELETE TO authenticated
  USING (auth.uid() = provider_id);
CREATE POLICY "Providers can select own schedule" ON provider_schedules
  FOR SELECT TO authenticated
  USING (auth.uid() = provider_id);

-- Upsert RPC to add or update a schedule slot (id optional)
CREATE OR REPLACE FUNCTION public.upsert_provider_schedule(
  p_id BIGINT,
  p_provider_id UUID,
  p_day_of_week SMALLINT,
  p_start_time TIME,
  p_end_time TIME
) RETURNS VOID AS $$
BEGIN
  IF p_id IS NULL THEN
    INSERT INTO provider_schedules (provider_id, day_of_week, start_time, end_time)
    VALUES (p_provider_id, p_day_of_week, p_start_time, p_end_time);
  ELSE
    UPDATE provider_schedules
    SET day_of_week = p_day_of_week,
        start_time = p_start_time,
        end_time = p_end_time,
        updated_at = NOW()
    WHERE id = p_id AND provider_id = p_provider_id;
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION public.upsert_provider_schedule(BIGINT, UUID, SMALLINT, TIME, TIME) TO authenticated;

-- End of migration